import { auth } from "@/auth";
import { LoopsClient } from "loops";
import { NextResponse } from "next/server";

const loops = new LoopsClient(process.env.LOOPS_API_KEY!);

export async function POST(req: Request) {
  const session = await auth();
  if (!session?.user?.email) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { analysis, appId } = await req.json();

  if (!analysis) {
    return NextResponse.json({ error: "Analysis data required" }, { status: 400 });
  }

  try {
    // Construct HTML content for the report
    const htmlContent = `
      <h1>Weekly Pulse: ${appId}</h1>
      
      <h2>Top 5 Themes</h2>
      <ul>
        ${analysis.themes.map((t: string) => `<li>${t}</li>`).join("")}
      </ul>
      
      <h2>User Voices</h2>
      ${analysis.quotes.map((q: any) => `
        <div style="margin-bottom: 10px; padding: 10px; border-left: 3px solid #00D09C; background: #f9f9f9;">
          <p>"${q.text}"</p>
          <small>${q.rating} ⭐ - ${q.time}</small>
        </div>
      `).join("")}
      
      <h2>Action Items</h2>
      <ul>
        ${analysis.action_items.map((a: string) => `<li>${a}</li>`).join("")}
      </ul>
      
      <p>Generated by App-Prism</p>
    `;
    const response = await loops.sendTransactionalEmail({
      transactionalId: "app-prism-weekly-mail",
      email: session.user.email,
      dataVariables: {
        appId,
        reportHtml: htmlContent,
      },
    });

    return NextResponse.json({ success: true, data: response });

  } catch (error) {
    console.error("Email error:", error);
    return NextResponse.json({ error: "Failed to send email" }, { status: 500 });
  }
}
